name: Run Gradle on Push/PRs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
    
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        arguments: build --scan --gradle-user-home ${{github.workspace}} /app

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: ${{github.workspace}} /app/build/outputs/apk/release/app-release.apk
